### ISSUE TITLE
Compute best fetch dependency graph given the options for each branch (query plan business logic)

### ISSUE THREAD

**Issue by sachindshinde** [apollographql/federation-next#77] opened 2023-11-03 16:24 UTC
This GH issue is the first part of https://github.com/apollographql/federation-next/issues/31 .

Specifically:
- Pruning the options for each branch.
- Generating the initial partial fetch dependency graph and remaining options.
- Iterating through all possible fetch dependency graphs from the initial one, and returning the one with best cost.

More specifically, this issue is for porting `QueryPlanningTraversal.computeBestPlanFromClosedBranches()` and its code dependencies.

**Comment by hwillson** [comment] 2023-11-09 19:16
Something to consider - can @sachindshinde pair with @SimonSapin on this work, to make sure we're cross-pollinating?

**Comment by abernix** [comment] 2023-11-16 15:35
@sachindshinde can you drop links to the relevant JS code? thx!

**Comment by lrlna** [comment] 2024-01-30 16:49
closing as duplicate of smaller issues.

**Closed by lrlna** 2024-01-30 16:49 UTC
