### ISSUE TITLE
Generate query plan from fetch dependency graph (query plan business logic)

### ISSUE THREAD

**Issue by sachindshinde** [apollographql/federation-next#78] opened 2023-11-03 16:30 UTC
This GH issue is the second part of https://github.com/apollographql/federation-next/issues/31 .

Specifically:
- Reducing and optimizing the fetch dependency graph.
- Generating a query plan from the reduced fetch dependency graph.

More specifically, this issue is for porting `FetchDependencyGraph.process()` and its code dependencies.
```[tasklist]
### Tasks
- [ ] https://github.com/apollographql/federation-next/issues/149
- [ ] https://github.com/apollographql/federation-next/issues/150
- [ ] https://github.com/apollographql/federation-next/issues/151
```

**Comment by hwillson** [comment] 2023-11-09 19:16
Something to consider - can @sachindshinde pair with @SimonSapin on this work, to make sure we're cross-pollinating?

**Comment by lrlna** [comment] 2024-01-30 16:49
closing as duplicate of smaller issues.

**Closed by lrlna** 2024-01-30 16:49 UTC
